### ISSUE TITLE
[Bug] TypeError: Cannot set properties of undefined (setting 'leafArticles')

### ISSUE THREAD

**Issue by lizzxrd** [tgabi333/youtrack-article-export#2]
Hey it`s me again :) 

Two of scrips work well, even better than i expected! 
But the `project.js` script causes some difficulties.

Case: 
I tried to export article  that contains two other sub-articles (not the whole project) but all i got is some strange info and no errors:
```
node project.js --project <my_arcticle_ID>

all articles count: 389

project articles count: 0

```
When i tried to export whole project i got this error:
```
# node project.js --project <my_project>                  

all articles count: 389

project articles count: 224

/root/youtrack-article-export/lib/helpers/generatePdf.js:56

  root.leafArticles = []
                    ^
TypeError: Cannot set properties of undefined (setting 'leafArticles')

    at generatePdfDocumentation (/root/youtrack-article-export/lib/helpers/generatePdf.js:56:21)

    at /root/youtrack-article-export/project.js:36:13

    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

```

And when i tried to start this script with `--filter` flag as it was mentioned in the help-info with;
```
# node project.js --project <my_project>  --filter <my_arcticle_ID>

```
I got the same output as above.

Maybe you could check what causes this error?

**Comment by lizzxrd** [comment]
I did some changes. So if you`re interested you could check it in my fork
